=== JesusAlfredoCobosValencia/ordinario-ftw/xml/usuarios.dtd
<!ELEMENT usuarios (usuario+)>
<!ELEMENT usuario (nombre, clave, tipo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT clave (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

=== JesusAlfredoCobosValencia/ordinario-ftw/xml/usuarios.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE usuarios SYSTEM "usuarios.dtd">

<usuarios>
    <usuario>
        <nombre>admin</nombre>
        <clave>1234</clave>
        <tipo>Administrador</tipo>
    </usuario>

    <usuario>
        <nombre>invitado</nombre>
        <clave>1111</clave>
        <tipo>Invitado</tipo>
    </usuario>

    <usuario>
        <nombre>liga</nombre>
        <clave>2026</clave>
        <tipo>Usuario</tipo>
    </usuario>
</usuarios>
